# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_payee', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
