# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0003_auto_20170821_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
