# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Expenditure', '0004_auto_20170821_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='debits',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credits',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
