# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0006_auto_20170821_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debits',
            name='system',
        ),
        migrations.AddField(
            model_name='debits',
            name='sys_break',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='debits',
            name='sys_chasis',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='debits',
            name='sys_engine',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='debits',
            name='sys_misc',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='debits',
            name='sys_suspension',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='debits',
            name='unit',
            field=models.CharField(default=b'NA', max_length=10),
        ),
    ]
