# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0008_auto_20170823_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debits',
            name='sys_break',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='debits',
            name='sys_chasis',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='debits',
            name='sys_engine',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='debits',
            name='sys_misc',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='debits',
            name='sys_suspension',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='debits',
            name='tax',
            field=models.BooleanField(default=0),
        ),
    ]
