# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0009_auto_20170823_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debits',
            name='category',
            field=models.CharField(choices=[(b'Other', b'Other'), (b'Cat1', b'Cat1'), (b'Cat2', b'Cat2'), (b'Cat3', b'Cat3')], default=b'Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='debits',
            name='unit',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'Lt', b'Ltr'), (b'Kg', b'Kg'), (b'Mt', b'Mtr'), (b'Gr', b'Gram'), (b'Ng', b'Nugs')], default=b'NA', max_length=10),
        ),
    ]
