# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0010_auto_20170902_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debits',
            name='sys_break',
            field=models.BooleanField(),
        ),
    ]
