# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0011_auto_20170902_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debits',
            name='sys_chasis',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='debits',
            name='sys_engine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='debits',
            name='sys_misc',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='debits',
            name='sys_suspension',
            field=models.BooleanField(),
        ),
    ]
