# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0012_auto_20170902_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debits',
            name='tax',
            field=models.BooleanField(),
        ),
    ]
