# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0014_auto_20180221_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
