# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0017_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='system',
        ),
    ]
