# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0018_remove_user_info_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='assets',
        ),
    ]
