# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0019_remove_user_info_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='assets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.CharField(help_text=b'Enter 10 digit Mobile Number', max_length=16),
        ),
    ]
