# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0021_auto_20180223_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debits',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expenditure.Category'),
        ),
    ]
