# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0022_auto_20180223_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debits',
            name='sys_break',
        ),
        migrations.RemoveField(
            model_name='debits',
            name='sys_chasis',
        ),
        migrations.RemoveField(
            model_name='debits',
            name='sys_engine',
        ),
        migrations.RemoveField(
            model_name='debits',
            name='sys_misc',
        ),
        migrations.RemoveField(
            model_name='debits',
            name='sys_suspension',
        ),
        migrations.AddField(
            model_name='debits',
            name='system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Expenditure.System'),
        ),
        migrations.AlterField(
            model_name='debits',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Expenditure.Category'),
        ),
    ]
