# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0027_auto_20180313_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balence',
            old_name='current_balence',
            new_name='balence',
        ),
        migrations.RemoveField(
            model_name='balence',
            name='event',
        ),
        migrations.RemoveField(
            model_name='balence',
            name='total_balence',
        ),
    ]
