# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0030_auto_20180313_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balence',
            name='event',
        ),
    ]
