# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0031_remove_balence_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='balence',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Expenditure.Event'),
        ),
    ]
