# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0032_balence_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 13, 16, 54, 11, 156227, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='debits',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 13, 16, 54, 11, 154593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 13, 16, 54, 11, 152697, tzinfo=utc)),
        ),
    ]
