# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0036_auto_20180313_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='subevent_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
