# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0037_auto_20180314_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
    ]
