# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0038_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debits',
            name='event',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Expenditure.Event'),
        ),
    ]
